import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./Components/NavBar";
import Footer from "./Components/Footer";

export const metadata: Metadata = {
  title: "YH Jang | HOME",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar></NavBar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
