import { BottomNav } from "@/components/BottomNav";
import Footer from "@/components/Footer";
import { NavBar } from "@/components/NavBar";
import "@/styles/globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "YH Jang | HOME",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="h-screen flex flex-col bg-white dark:bg-gray-900 text-gray-900 dark:text-white">
        <NavBar />
        <main className="flex-grow overflow-y-auto">{children}</main>
        <Footer />
        <BottomNav /> {/* 모바일 하단 전용 네비게이션 */}
      </body>
    </html>
  );
}
