import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "YH Jang | HOME",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col bg-white dark:bg-gray-900 text-gray-900 dark:text-white">
        <NavBar />
        <main className="flex-grow overflow-y-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}